/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface EscrowInterface extends Interface {
    getFunction(nameOrSignature: "buyer" | "currentState" | "deposit" | "escrowAgent" | "makeDelivery" | "refundFundsToBuyer" | "releaseFundsToSeller" | "seller" | "x"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'buyer', values?: undefined): string;
encodeFunctionData(functionFragment: 'currentState', values?: undefined): string;
encodeFunctionData(functionFragment: 'deposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'escrowAgent', values?: undefined): string;
encodeFunctionData(functionFragment: 'makeDelivery', values?: undefined): string;
encodeFunctionData(functionFragment: 'refundFundsToBuyer', values?: undefined): string;
encodeFunctionData(functionFragment: 'releaseFundsToSeller', values?: undefined): string;
encodeFunctionData(functionFragment: 'seller', values?: undefined): string;
encodeFunctionData(functionFragment: 'x', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'buyer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrowAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'makeDelivery', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundFundsToBuyer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseFundsToSeller', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'seller', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'x', data: BytesLike): Result;
  }

  

  export interface Escrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): Escrow;
    waitForDeployment(): Promise<this>;

    interface: EscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    buyer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    currentState: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    escrowAgent: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    makeDelivery: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    refundFundsToBuyer: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    releaseFundsToSeller: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    seller: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    x: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'buyer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'currentState'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'escrowAgent'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'makeDelivery'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'refundFundsToBuyer'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseFundsToSeller'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'seller'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'x'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }